apiVersion: v1
kind: Service
metadata:
  name: nginx-service1
  labels:
    app: nginx1
spec:
  type: NodePort
  selector:
    app: nginx1
  ports:
  - port: 80
    nodePort: 30001
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - name: nginx
    image: repocurso:9091/nginx
  imagePullSecrets:
  - name: registry-credential
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service2
  labels:
    app: nginx2
spec:
  type: NodePort
  selector:
    app: nginx2
  ports:
  - port: 80
    nodePort: 30002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx2
spec:
  selector:
    matchLabels:
      app: nginx2
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx2
    spec:
      containers:
      - name: my-app
        image: repocurso:9091/nginx
        ports:
        - name: nginx-dep-port
          containerPort: 80
      imagePullSecrets:
      - name: registry-credential

