Vagrant.configure('2') do |config|
  vm_box = "centos/7"
  config.vm.define :host, primary: true  do |host|
    host.vm.box = vm_box
    host.vm.box_check_update = true
    host.vm.network :private_network, ip: "192.168.33.11"
    host.vm.hostname = "centos"
    #host.vm.synced_folder ".", "/vagrant"
    host.vm.provider "virtualbox" do |vb|
      vb.name = "docker-centos"
      vb.memory = "1024"
      vb.cpus = "2"
    end
  end
end
