Vagrant.configure('2') do |config|
  vm_box = "bento/ubuntu-22.04"
  config.vm.boot_timeout = 600
  config.vm.define :ubuntu, primary: true  do |ubuntu|
    ubuntu.vm.box = vm_box
    ubuntu.vm.box_check_update = true
    ubuntu.vm.network :private_network, ip: "192.168.100.12", :libvirt__domain_name => "curso.local", :libvirt__dhcp_enabled => false, :libvirt__network_name => "red-entornos"
    ubuntu.vm.hostname = "ubuntu"
    ubuntu.vm.synced_folder "~/curso/shared/repository/", "/vagrant", type: "nfs", nfs_version: 4
    ubuntu.vm.provider "libvirt" do |vb|
      #vb.name = "docker-ubuntu"
      vb.memory = "1024"
      vb.cpus = "2"
    end
  end
end
