Vagrant.configure('2') do |config|
  vm_box = "bento/ubuntu-22.04"
  config.vm.define :host, primary: true  do |host|
    host.vm.box = vm_box
    host.vm.box_check_update = true
    host.vm.network :private_network, ip: "192.168.33.12"
    host.vm.hostname = "ubuntu"
    host.vm.synced_folder ".", "/vagrant"
    host.vm.provider "virtualbox" do |vb|
      vb.name = "docker-ubuntu"
      vb.memory = "1024"
    end
  end
end
