Vagrant.configure('2') do |config|
  vm_box = "bento/ubuntu-22.04"
  config.vm.define :ubuntu, primary: true  do |ubuntu|
    ubuntu.vm.box = vm_box
    ubuntu.vm.box_check_update = true
    ubuntu.vm.network :private_network, ip: "192.168.33.12"
    ubuntu.vm.hostname = "ubuntu"
    ubuntu.vm.synced_folder ".", "/vagrant"
    ubuntu.vm.provider "virtualbox" do |vb|
      vb.name = "docker-ubuntu"
      vb.memory = "1024"
      vb.cpus = "2"
    end
  end
end
