$install_docker_script = <<SCRIPT
echo Installing Docker...
curl -sSL https://get.docker.com/ | sh
usermod -aG docker vagrant
SCRIPT

$repo_script = <<SCRIPT
echo Repository Init...
mkdir -p /nexus/nexus-data/instances && sudo chmod 777 -R /nexus/ && sudo setfacl -R -d -m u::rwx -m g::rwx -m o::rwx /nexus/
docker run --name nexus --restart="always" -d -p 8081:8081 -p 9091:9091 -v /nexus/nexus-data:/nexus-data sonatype/nexus3
SCRIPT

Vagrant.configure('2') do |config|
  vm_box = 'bento/ubuntu-22.04'

  config.vm.define :repository, primary: true  do |repository|
    repository.vm.box = vm_box
    repository.vm.box_check_update = true
    repository.vm.network :private_network, ip: "192.168.100.200"
    repository.vm.network :forwarded_port, guest: 8081, host: 8081
    repository.vm.network :forwarded_port, guest: 9091, host: 9091
    repository.vm.hostname = "repository"
    repository.vm.synced_folder ".", "/vagrant"
    repository.vm.provision "shell", inline: $install_docker_script, privileged: true
    repository.vm.provision "shell", inline: $repo_script, privileged: true
    repository.vm.provider "virtualbox" do |vb|
      vb.name = "repository"
      vb.memory = "1024"
    end
  end
end
