# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.provider :libvirt do |libvirt|
    libvirt.driver = "kvm"
    libvirt.cpus = 2
    libvirt.memory = 8192
  end
  #config.vm.synced_folder "~/shared/", "/vagrant", type: "9p", disabled: false, accessmode: "squash", owner: "0"
  #config.vm.synced_folder "./", "/vagrant", type: "9p", disabled: false, accessmode: "mapped", mount: false
  config.vm.synced_folder "~/curso/shared/x/", "/vagrant", type: "nfs", nfs_version: 4
end
