Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.network "private_network", ip: "192.168.100.150"
  config.vm.hostname = "kind"
  config.vm.provision :shell, path: "./scripts/01-bootstrap.sh"
  config.vm.provision :shell, path: "./scripts/02-kind-cluster.sh"
  config.vm.provision :shell, path: "./scripts/03-node-prepare.sh"
  config.vm.provision :shell, path: "./scripts/04-ssh-config.sh"
  config.vm.provision :shell, path: "./scripts/05-docker-install.sh"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 8192
    vb.cpus = 4
    vb.name = "kind"
  end
end
